mlflow:
  experiment: sbsbs
  run: test

opt:
  learning_rate: 0.1
  num_epochs: 200
  batch_size: 1
  decay_steps: 100000
  method: scipy
  metric_time_in_ps: 6.0

# trainable_params:
#   Jr_target: [0.1,0.1,0.1,0.1]

units:
  atomic mass number: 13.0
  laser_intensity: 8.0e+15W/cm^2
  laser_wavelength: 351nm
  reference temperature: 1000.0eV
  reference density: nc  # or it can be a float value
  Z_eff: 4.0  # effective charge, TODO: needs to be adjustable in profiles
  logLambda: nrl
  
leh:
  spec:
    n_steps: 10000
  profile:
    n_over_n0: 0.05  # normalized density profile
    Te_over_T0: 1.5  # electron temperature over ion temperature ratio
    Ti_over_T0: 0.5  # ion temperature over ion temperature ratio
    A_ion: 4.0  # ion mass number
    flow_magnitude: 1.0e-4  # flow magnitude in units of u/c
    flow_theta: 0.0  # flow polar angle in degrees
    flow_phi: 0.0  # flow azimuthal angle in radians
    L_p: 600.0  # plasma length in units of lambda
  # grid:
  #   n_steps: 10000

laser:
  wavelength: 3510  # Angstrom
  # beam_file: /path/to/beam_file.txt  # path to the beam file
  # a0_sq: 1e-6  # initial a_0^2, assuming all beams have same initial intensity
  num_beams: 4

beam:
  "0":
    spec:
      dz: 10um
      zmax: 1cm
      theta: 23.5  # polar angle in degrees
      phi: 0.0  # azimuthal angle in radians
      dl: 0.0  # dlambda/lambda
    profile:
      n_min: 0.001nc
      n_max: 0.025nc
      Te: 1.4keV
      Ti: 450eV
      flow: 0.0m/s
      lambdabeat: 5.293519e-10m
      thermal_noise: 0.1
  "1":
    spec:
      dz: 10um
      zmax: 1cm
      theta: 30  # polar angle in degrees
      phi: 0.0  # azimuthal angle in radians
      dl: 0.0  # dlambda/lambda
    profile:
      n_min: 0.001nc
      n_max: 0.025nc
      Te: 1.4keV
      Ti: 450eV
      flow: 0.0m/s
      lambdabeat: 5.293519e-10m
      thermal_noise: 0.1
  "2":
    spec:
      dz: 10um
      zmax: 1cm
      theta: 44.5  # polar angle in degrees
      phi: 0.0  # azimuthal angle in radians
      dl: 1.8  # dlambda/lambda
    profile:
      n_min: 0.001nc
      n_max: 0.025nc
      Te: 1.4keV
      Ti: 450eV
      flow: 0.0m/s
      lambdabeat: 5.293519e-10m
      thermal_noise: 0.1
  "3":
    spec:
      dz: 10um
      zmax: 1cm
      theta: 50  # polar angle in degrees
      phi: 0.0  # azimuthal angle in radians
      dl: 1.8  # dlambda/lambda
    profile:
      n_min: 0.001nc
      n_max: 0.025nc
      Te: 1.4keV
      Ti: 450eV
      flow: 0.0m/s
      lambdabeat: 5.293519e-10m
      thermal_noise: 0.1


# sbs:
#   grid:
#     "0":
#       dz: 10um
#       zmax: 1cm
#     "1":
#       dz: 10um
#       zmax: 1cm
#     "2":
#       dz: 10um
#       zmax: 1cm
#     "3":
#       dz: 10um
#       zmax: 1cm
  
#   profiles:
#     "0":
#       n: 
#         min: 0.001nc
#         max: 0.025nc
#       Te: 1.4keV
#       Ti: 450eV
#       flow: 0.0m/s
#       lambdabeat: 5.293519e-10m
#     "1":
#       n: 
#         min: 0.001nc
#         max: 0.025nc
#       Te: 1.4keV
#       Ti: 450eV
#       flow: 0.0m/s
#       lambdabeat: 5.293519e-10m
#     "2":
#       n: 
#         min: 0.001nc
#         max: 0.025nc
#       Te: 1.4keV
#       Ti: 450eV
#       flow: 0.0m/s
#       lambdabeat: 5.293519e-10m
#     "3":
#       n: 
#         min: 0.001nc
#         max: 0.025nc
#       Te: 1.4keV
#       Ti: 450eV
#       flow: 0.0m/s
#       lambdabeat: 5.293519e-10m

# # cbet:
# #   profiles:
# #     n_over_n0: 0.05  # normalized density profile
# #     Te_over_T0: 1.5  # electron temperature over ion temperature ratio
# #     Ti_over_T0: 0.5  # ion temperature over ion temperature ratio
# #     A_ion: 4.0  # ion mass number
# #     flow_magnitude: 1.0e-4  # flow magnitude in units of u/c
# #     flow_theta: 0.0  # flow polar angle in degrees
# #     flow_phi: 0.0  # flow azimuthal angle in radians
# #     L_p: 600.0  # plasma length in units of lambda
# #   grid:
# #     n_steps: 10000

# laser:
#   wavelength: 3510  # Angstrom
#   # beam_file: /path/to/beam_file.txt  # path to the beam file
#   # a0_sq: 1e-6  # initial a_0^2, assuming all beams have same initial intensity
#   num_beams: 4
#   beams:
#     "0":
#       theta: 23.5  # polar angle in degrees
#       phi: 0.0  # azimuthal angle in radians
#       dl: 0.0  # dlambda/lambda
#     "1":
#       theta: 30.0  # polar angle in degrees
#       phi: 0.0  # azimuthal angle in radians
#       dl: 0.0  # dlambda/lambda
#     "2":
#       theta: 44.5  # polar angle in degrees
#       phi: 0.0  # azimuthal angle in radians
#       dl: 1.8  # dlambda/lambda
#     "3":
#       theta: 50.0  # polar angle in degrees
#       phi: 0.0  # azimuthal angle in radians
#       dl: 1.8  # dlambda/lambda
