mode: es-1d

mlflow:
  experiment: wavepackets-for-fluid
  run: single-k=0.3-finite-amplitude-fluid-trapping

grid:
    nx: 6144
    xmin: 0.0
    xmax: 6000
    tmin: 0.0
    tmax: 1000.0

save:
    func:
        is_on: True
    t:
      tmin: 0.0
      tmax: 1000.0
      nt: 2001
    x:
      is_on: True
      xmin: 0.0
      xmax: 4000.0
      nx: 1024
    kx:
      is_on: True
      kxmin: 0.0
      kxmax: 0.5
      nkx: 21

models:
    file: models/weights.eqx
    nu_g:
        in_size: 3
        out_size: 1
        width_size: 8
        depth: 4
        activation: tanh
        final_activation: tanh
#    nu_d:
#        in_size: 3
#        out_size: 1
#        width_size: 8
#        depth: 3
#        activation: tanh
#        final_activation: tanh


physics:
    ion:
      is_on: False
      mass: 1836.0
      gamma: 3.0
      charge: 1.0
      T0: 0.1
      landau_damping: False
      trapping:
        is_on: False
        kld: 0.3
        nuee: 1.0e-9
    electron:
      is_on: True
      mass: 1.0
      T0: 1.0
      gamma: 3.0
      charge: -1.0
      landau_damping: True
      trapping:
        is_on: True
        kld: 0.3
        nuee: 1.1e-5

drivers:
  "ex":
    "0":
      "k0": 0.3
      "w0": 1.1598
      "dw0": 0.0
      "t_c": 80
      "t_w": 100
      "t_r": 20
      "x_c": 600
      "x_w": 800
      "x_r": 80
      "a0": 4.e-3
    "1":
      "k0": 0.26
      "w0": 1.11
      "dw0": 0.0
      "t_c": 400
      "t_w": 100
      "t_r": 20
      "x_c": 2000
      "x_w": 800
      "x_r": 80
      "a0": 0.e-2

